### ISSUE TITLE
Cannot unset welcome.html set in extraFileMappings to prefer the one in the container

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#121]
I have a container based on galaxy/galaxy-k8s:20.01 where I have our branding in welcome.html. However, I cannot seem to unset the one being added by the chart to prefer the one in the container. I have tried:

```
extraFileMappings: {}
```

```
extraFileMappings:
  /galaxy/server/static/welcome.html: ~
```

and

```
extraFileMappings:
  /galaxy/server/static/welcome.html:
    useSecret: false
    applyToJob: false
    applyToWeb: true
    content: ~
```

but I always end up with the one added by the chart (you can tell by the modification date of the file).

I was expecting the first one to work... any advice?
