### ISSUE TITLE
underlying postgres chart not responding to livenessProbes and readinessProbes changes

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#36]
When I set:

```
postgresql:
  imageTag: "9.6.5_for_18.05"
  livenessProbe:
    initialDelaySeconds: 1500
  readinessProbe:
    initialDelaySeconds: 1500
```

the probes don't change. Probably an underlying issue of the postgres chart. Apparently stable/postgres has advanced a lot but now geared for postgres 10, so we might want to be careful with that change to keep support for older versions.
