### ISSUE TITLE
Cannot Download output file from Galaxy

### ISSUE THREAD

**Issue by DuttaAnik** [galaxyproject/galaxy-helm#461]
![Capture](https://github.com/galaxyproject/galaxy-helm/assets/41111038/7531853d-e52e-4299-820c-93ce65ce33a4)
Hello,

I have successfully installed Galaxy and deployed it in the Kubernetes cluster. I ran some analysis using Prokka and it completed the analysis and produced some output files. But I cannot download the output files. If I click on the download button, I receive an error message. I have attached the error message. Could anybody please suggest how to solve this issue?

This is the value.yaml file:
```
galaxy:
  fullnameOverride: galaxy
  nameOverride: galaxy
  revisionHistoryLimit: 3
  images:
    galaxy:
      repository: quay.io/galaxyproject/galaxy-min
      tag: "23.1"  # Value must be quoted
      pullPolicy: IfNotPresent
  refdata:
   enabled: false
   type: cvmfs
   pvc:
     size: 10Gi
  cvmfs:
    deploy: false
    storageClassName: "{{ $.Release.Name }}-cvmfs"
  persistence:
    enabled: true
    name: galaxy-pvc
    annotations: {}
    storageClassName: XXX
    existingClaim: galaxy-kubernetes-pvc
    accessMode: ReadWriteMany
    size: 200Gi
    mountPath: /galaxy/server/database
  rabbitmq:
    enabled: true
    deploy: true
    persistence:
      storageClassName: XXX
  celery:
    concurrency: 1
  postgresql:
    enabled: true
    deploy: true
    galaxyDatabaseUser: postgres
    galaxyDatabasePassword: XXXXXX
  configs:
    galaxy.yml:
      galaxy:
        admin_users: XX@xx.com
```
This is the ingress.yaml file:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: galaxy.XX.XX.cloud
  namespace: galaxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: galaxy.XX.XX.cloud
      http:
        paths:
          - backend:
              service:
                name: galaxy-nginx
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - galaxy.XX.XX.cloud
      secretName: galaxy.XX.XX.cloud
```

It would be great if you could provide me with any guidance.
TIA

**Comment by nuwang** [comment]
Can you show your configuration for the ingress section in values.yaml? By default, it's configured to run under the `/galaxy` prefix, but looking at your ingress, it looks like it's running under /. If so, you should configure he ingress values to match as follows:
```
ingress:
  path: /
  hosts:
    - host: ~
      paths:
        - path: "/"
        - path: "/training-material"
```

If that's not configured, the galaxy internal nginx server could be picking up the wrong prefix when serving datasets, hence the issue with datasets only.

**Comment by DuttaAnik** [comment]
I do not have any ingress section in the value.yaml file. I have pasted the whole values.yaml file above. Should I copy the ingress code that you just shared?

**Comment by nuwang** [comment]
Aah, that probably explains it - I take it you created the ingress shown above by hand? You can get the helm chart to create the ingress for you by setting values appropriately. And yes, you can use the values shown above, but will probably also need to include a tls section and set the host value + annotations to match your environment. Take a look at the values.yaml for sample values.

**Comment by DuttaAnik** [comment]
Hi @nuwang thanks for the helpful tips. Yes, I have created the ingress file by hand. How can I get the helm chart to create the ingress file? Could you please explain? Sorry, I am new in this field. So, maybe I am not understanding the simple things.
I got this following section from the original values-org.yaml file from the galaxy github.
```
ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/connection-proxy-header: "Upgrade"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - host: ~
        paths:
          - path: "/galaxy/api/upload/resumable_upload"
    tls: []


```

**Comment by nuwang** [comment]
I think you've extracted the tusd section. The main section you need to modify is here:
https://github.com/galaxyproject/galaxy-helm/blob/0afe341dcae427832ac232c8d87c842436daf971/galaxy/values.yaml#L270

And afterwards. you can update the tusd section to match.

Something like:
```
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  path: /
  hosts:
    - host: galaxy.XX.XX.cloud
      paths:
        - path: "/"
        - path: "/training-material"
  tls:
    - hosts:
        - galaxy.XX.XX.cloud
      secretName: galaxy.XX.XX.cloud
```

**Comment by DuttaAnik** [comment]
Hello @nuwang Thanks for the suggestions. I have modified the values.yaml file like below:
```
galaxy:
  fullnameOverride: galaxy
  nameOverride: galaxy
  revisionHistoryLimit: 3
  images:
    galaxy:
      repository: quay.io/galaxyproject/galaxy-min
      tag: "23.1"  # Value must be quoted
      pullPolicy: IfNotPresent
  refdata:
    enabled: false
    type: cvmfs
    pvc:
      size: 10Gi
  cvmfs:
    deploy: false
    storageClassName: "{{ $.Release.Name }}-cvmfs"
  persistence:
    enabled: true
    name: galaxy-pvc
    annotations: {}
    storageClassName: freenas-nfs-csi
    existingClaim: galaxy-k3s-rdloc-galaxy-pvc
    accessMode: ReadWriteMany
    size: 200Gi
    mountPath: /galaxy/server/database
  rabbitmq:
    enabled: true
    deploy: true
    persistence:
      storageClassName: freenas-iscsi-csi
  celery:
    concurrency: 1
  postgresql:
    enabled: true
    deploy: true
    galaxyDatabaseUser: postgres
    galaxyDatabasePassword: password
  configs:
    galaxy.yml:
      galaxy:
        admin_users: f@ss.com

# The suggested ingress configuration to be added to the values.yaml:
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: galaxy.XX.XX.cloud
      paths:
        - path: /
          pathType: Prefix
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - galaxy.XX.XX.cloud
      secretName: galaxy.XX.XX.cloud

tusd:
  enabled: true  

  ingress:
    enabled: true
    annotations:
      
    hosts:
      - host: galaxy.XX.XX.cloud
        paths:
          - path: /
            pathType: Prefix
```
But it did not solve the Download output files issue. I am still getting  the same error message that I showed.

Besides, there is another issue. After making these changes, I tried to upload a datafile in Galaxy and there is also an error message and the data file cannot be uploaded.

The error message is:
`/bin/bash: line 1: /galaxy/server/database/jobs_directory/000/42/galaxy_42.sh: No such file or directory `

This is the description file of the galaxy job from Kubernetes:
```

Name:                 gxy-galaxy-k3s-rdloc-ttmkc-4xdkq
Namespace:            galaxy
Priority:             -1000
Priority Class Name:  galaxy-job-priority
Service Account:      default
Node:                 xxx/xxxx
Start Time:           Mon, 08 Apr 2024 15:43:48 +0200
Labels:               app.galaxyproject.org/destination=k8s
                      app.galaxyproject.org/handler=job_handler_0
                      app.galaxyproject.org/job_id=41
                      app.kubernetes.io/component=tool
                      app.kubernetes.io/instance=gxy-galaxy-k3s-rdloc
                      app.kubernetes.io/managed-by=galaxy
                      app.kubernetes.io/name=x__DATA_FETCH__x
                      app.kubernetes.io/part-of=galaxy
                      app.kubernetes.io/version=0.1.0
                      batch.kubernetes.io/controller-uid=xxxx
                      batch.kubernetes.io/job-name=gxy-galaxy-k3s-rdloc-ttmkc
                      controller-uid=44343ed2-1e80-45fc-9b43-d474daea53d2
                      job-name=gxy-galaxy-k3s-rdloc-ttmkc
Annotations:          app.galaxyproject.org/tool_id: __DATA_FETCH__
Status:               Failed
IP:                   XX
IPs:
  IP:           XX
Controlled By:  Job/gxy-galaxy-k3s-rdloc-ttmkc
Containers:
  k8s:
    Container ID:  containerd://XX
    Image:         quay.io/galaxyproject/galaxy-min:23.1
    Image ID:      quay.io/galaxyproject/galaxy-min@sha256:XXX
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
    Args:
      -c
      /galaxy/server/database/jobs_directory/000/41/galaxy_41.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Mon, 08 Apr 2024 15:43:50 +0200
      Finished:     Mon, 08 Apr 2024 15:43:50 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  4080218931200m
    Requests:
      cpu:     1
      memory:  4080218931200m
    Environment:
      GALAXY_SLOTS:               1
      GALAXY_MEMORY_MB:           4080
      GALAXY_MEMORY_MB_PER_SLOT:  4080
    Mounts:
      /cvmfs/cloud.galaxyproject.org from galaxy-k3s-rdloc-galaxy-pvc (rw,path="cvmfsclone")
      /galaxy/server/database from galaxy-k3s-rdloc-galaxy-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rfcvn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  galaxy-k3s-rdloc-galaxy-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  galaxy-k3s-rdloc-galaxy-pvc
    ReadOnly:   false
  kube-api-access-rfcvn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 20s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 20s
Events:                      <none>
```

Can you please suggest how to overcome these issues? I am a bit lost as to where this error is originating from.
Thank you very much.

**Comment by DuttaAnik** [comment]
Any update @nuwang?

**Comment by almahmoud** [comment]
Hey @DuttaAnik. In your latest values, you seem to have changed the paths under `ingress.hosts.paths`, but not under `ingress.path` as shown in Nuwan's example. Also, you have two identical paths for `/`. There might be other issues which might be hard to diagnose without access to your cluster, but something to try that might help is replacing:

```
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: galaxy.XX.XX.cloud
      paths:
        - path: /
          pathType: Prefix
        - path: /
          pathType: Prefix
```

with 


```
ingress:
  path: /
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: galaxy.XX.XX.cloud
      paths:
        - path: /
          pathType: Prefix
```

and let us know if that changes anything.

**Comment by ksuderman** [comment]
What chart are you using to install Galaxy? The values you provided do not coincide with the values for the galaxy-helm chart.  For example, the root level `galaxy:` element and the galaxy-helm chart expects `persistence.storageClass` but you have `persistence.storageClassName`.  So you may want to check the PVC and make sure it is using the storage class it is supposed to be using. You mention having a `galaxy_ingress.yaml` file in the templates folder, if you set `ingress.enabled = true` in the values file that extra template may be causing conflicts when the Helm chart tries to setup an ingress.  You should likely use one or the other.

Also, what version of Kubernetes are you using?  I saw similar errors with Galaxy 23.x on later versions of Kubernetes due to an incompatibility with the version of `py-kube` used by Galaxy.  That was fixed in 24.0 so you may want to try that Galaxy version.

Finally, I don't think the `path` in your `tusd` section is correct.  It should likely be something like:
```
tusd:
    hosts:
      - host: galaxy.XXX.cloud
        paths:
          - path: /api/upload/resumable_upload
            pathType: Prefix
```

If that doesn't solve your problem can you `kubectl exec` into the job pod and check the owner and permissions of the files in `/galaxy/server/database/jobs_directory`.  Those should be owned by the `galaxy` user and Galaxy should be running as the `galaxy` user.

**Comment by DuttaAnik** [comment]
Hi @ksuderman thank you for the reply and sorry for the delayed response. The `Chart.yaml` I am using to install Galaxy looks like this:
```
apiVersion: v2
name: galaxy
type: application
version: 1.0.0
dependencies:
 - name: galaxy
   repository: https://github.com/CloudVE/helm-charts/raw/master
   version: 5.9.0
```
The Kubernetes version is: `v1.27.7+k3s2`

The YAML for the PVC that I created (pvc-galaxy-k3s-rdloc-galaxy-pvc.yaml
) looks like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: galaxy-k3s-rdloc
    app.kubernetes.io/name: galaxy
  name: galaxy-k3s-rdloc-galaxy-pvc
  namespace: galaxy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: freenas-nfs-csi
```

With the values.yaml file that I pasted in the first message, everything regarding the file upload was working smoothly, except the Downloading of output files. Then, I increased the PVC size to 400Gi from 100Gi but later on reduced to 200Gi. So, Once I increased the PVC to 400Gi, I could not reduce it. So, I deleted that PVC and created a new PVC with 200Gi. I checked with `kubectl` that the new PVC is there under the namespace of galaxy and the old one was removed. Then, I deployed again through ArgoCD and since then the upload does not work anymore.
I have also removed `ingress.enabled=true` from the values file and still it is not working. 

Finally, I did kubectl to look into the kubernetes job pod:
`kubectl describe pod galaxy-job-0-adad6b6c7-j9lc4 -n galaxy`
```
Name:             galaxy-job-0-adad6b6c7-j9lc4
Namespace:        galaxy
Priority:         0
Service Account:  galaxy
Node:             XXXX
Start Time:       Tue, 09 Apr 2024 11:16:08 +0200
Labels:           app.kubernetes.io/component=galaxy-job-handler
                  app.kubernetes.io/instance=galaxy-k3s-rdloc
                  app.kubernetes.io/name=galaxy
                  pod-template-hash=adad6b6c7
Annotations:      checksum/galaxy_conf: XXXX
                  checksum/galaxy_extras: aaaa
                  checksum/galaxy_rules: aaaaa
Status:           Running
IP:               XXX.XXX.XX
IPs:
  IP:           XXX.XXX.XX
Controlled By:  ReplicaSet/galaxy-job-0-adad6b6c7
Init Containers:
  galaxy-wait-db:
    Container ID:  containerd://e5e4f307e99927a68cc28c00d1129126d791bb949d7791c9adab5a71fed920d5
    Image:         quay.io/galaxyproject/galaxy-min:23.1
    Image ID:      quay.io/galaxyproject/galaxy-min@sha256:aac7ab9f8f9422b76f62344c02ddc8772a1ee893accbfebf98ad7e9d7bfcaf6e
    Port:          <none>
    Host Port:     <none>
    Args:
      sh
      -c
      until [ -f /galaxy/server/config/mutable/db_init_done_1 ]; do echo "waiting for DB initialization"; sleep 1; done; until timeout 1 bash -c "echo > /dev/tcp/galaxy-k3s-rdloc-rabbitmq-server/5672"; do echo "waiting for rabbitmq service"; sleep 1; done; until [ -f /galaxy/server/config/mutable/init_mounts_done_1 ]; do echo "waiting for copying onto NFS"; sleep 1; done; until [ -f /galaxy/server/config/mutable/init_clone_done_1 ]; do echo "waiting for refdata copying"; sleep 1; done; echo "Initialization waits complete"; sleep 5;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 09 Apr 2024 11:16:12 +0200
      Finished:     Tue, 09 Apr 2024 11:16:17 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /galaxy/server/config/mutable/ from galaxy-data (rw,path="config")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mcsvz (ro)
Containers:
  galaxy-job-0:
    Container ID:  containerd://a90ac9a121caef579f6911deddf633996e6c123cc6cce3db20125f155ae6909e
    Image:         quay.io/galaxyproject/galaxy-min:23.1
    Image ID:      quay.io/galaxyproject/galaxy-min@sha256:aac7ab9f8f9422b76f62344c02ddc8772a1ee893accbfebf98ad7e9d7bfcaf6e
    Port:          <none>
    Host Port:     <none>
    Args:
      sh
      -c
      python /galaxy/server/scripts/galaxy-main -c $GALAXY_CONFIG_FILE --server-name job_handler_0 --attach-to-pool job-handlers
    State:          Running
      Started:      Tue, 09 Apr 2024 11:16:18 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:                3
      ephemeral-storage:  10Gi
      memory:             7G
    Requests:
      cpu:                100m
      ephemeral-storage:  1Gi
      memory:             1G
    Liveness:             exec [sh -c python /tmp/probedb.py -c $GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION -s job_handler_0 -o $HOSTNAME] delay=0s timeout=5s period=10s #success=1 #failure=30
    Readiness:            exec [sh -c python /tmp/probedb.py -c $GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION -s job_handler_0 -o $HOSTNAME] delay=0s timeout=5s period=10s #success=1 #failure=12
    Startup:              exec [sh -c python /tmp/probedb.py -c $GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION -s job_handler_0 -o $HOSTNAME] delay=30s timeout=5s period=5s #success=1 #failure=80
    Environment:
      POD_NAME:                                         galaxy-job-0-adad6b6c7-j9lc4 (v1:metadata.name)
      GALAXY_DB_USER_PASSWORD:                          <set to the key 'password' in secret 'postgres.galaxy-galaxy-postgresql.acid.zalando.net'>  Optional: false
      GALAXY_CONFIG_OVERRIDE_DATABASE_CONNECTION:       postgresql://postgres:$(GALAXY_DB_USER_PASSWORD)@galaxy-galaxy-k3s-rdloc-postgres/galaxy?sslmode=require
      GALAXY_CONFIG_OVERRIDE_ID_SECRET:                 <set to the key 'galaxy-config-id-secret' in secret 'galaxy-k3s-rdloc-galaxy-secrets'>  Optional: false
      PYTHONPATH:                                       /galaxy/server/lib
      GALAXY_CONFIG_FILE:                               /galaxy/server/config/galaxy.yml
      GALAXY_RABBITMQ_USERNAME:                         <set to the key 'username' in secret 'galaxy-k3s-rdloc-rabbitmq-server-default-user'>  Optional: false
      GALAXY_RABBITMQ_PASSWORD:                         <set to the key 'password' in secret 'galaxy-k3s-rdloc-rabbitmq-server-default-user'>  Optional: false
      GALAXY_CONFIG_OVERRIDE_AMQP_INTERNAL_CONNECTION:  amqp://$(GALAXY_RABBITMQ_USERNAME):$(GALAXY_RABBITMQ_PASSWORD)@galaxy-k3s-rdloc-rabbitmq-server:5672
    Mounts:
      /cvmfs/cloud.galaxyproject.org from galaxy-data (rw,path="cvmfsclone")
      /galaxy/server/config/build_sites.yml from galaxy-conf-files (rw,path="build_sites.yml")
      /galaxy/server/config/container_resolvers_conf.xml from galaxy-conf-files (rw,path="container_resolvers_conf.xml")
      /galaxy/server/config/galaxy.yml from galaxy-conf-files (rw,path="galaxy.yml")
      /galaxy/server/config/integrated_tool_panel.xml from galaxy-conf-files (rw,path="integrated_tool_panel.xml")
      /galaxy/server/config/job_conf.yml from galaxy-conf-files (rw,path="job_conf.yml")
      /galaxy/server/config/mutable/ from galaxy-data (rw,path="config")
      /galaxy/server/config/sanitize_allowlist.txt from galaxy-conf-files (rw,path="sanitize_allowlist.txt")
      /galaxy/server/config/tool_conf.xml from galaxy-conf-files (rw,path="tool_conf.xml")
      /galaxy/server/config/workflow_schedulers_conf.xml from galaxy-conf-files (rw,path="workflow_schedulers_conf.xml")
      /galaxy/server/database from galaxy-data (rw)
      /galaxy/server/lib/galaxy/jobs/rules/tpv_rules_local.yml from galaxy-job-rules (rw,path="tpv_rules_local.yml")
      /tmp/probedb.py from extra-files-probe-script (rw,path="probedb.py")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mcsvz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  extra-files-probe-script:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      galaxy-probedb-py
    Optional:  false
  galaxy-conf-files:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      galaxy-configs
    Optional:  false
  galaxy-job-rules:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      galaxy-job-rules
    Optional:  false
  galaxy-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  galaxy-k3s-rdloc-galaxy-pvc
    ReadOnly:   false
  kube-api-access-mcsvz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 20s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 20s
Events:                      <none>
```

So, the problem still persists.
