### ISSUE TITLE
tusd deployment does not manage extra volume as other deployment 

### ISSUE THREAD

**Issue by NilsKrattinger** [galaxyproject/galaxy-helm#502]
Hi,
It looks like tusd deployment doesn't handle extra-volume through `tpl` function. 
This make extra-volume name extrapolation harder.

This is probaly related to [tusd extra volume](https://github.com/galaxyproject/galaxy-helm/blob/f5534df9fd3925f592de171d26a6079f40cbabfa/galaxy/templates/deployment-tusd.yaml#L84C9-L86C19) missing `tpl` call.

*Logs*
---

**Values**: 
```yaml
  extraVolumes:
      - name: master-data
        persistentVolumeClaim:
           claimName: '{{ template "galaxy.fullname" $ }}-master-data-pvc'
```

**tusd-deployment** helm template export :
```yaml
  - name: master-data
    persistentVolumeClaim:
      claimName: '{{ template "galaxy.fullname" $ }}-master-data-pvc'
```

**web (or other)** helm template export:
```yaml
 - name: master-data
    persistentVolumeClaim:
      claimName: dev01-galaxy-master-data-pvc
```
